# Generated by Django 3.0.5 on 2020-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeanswer',
            name='state',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='state',
            field=models.NullBooleanField(default=None),
        ),
    ]
