# Generated by Django 3.0.5 on 2020-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200614_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.jpg', upload_to='uploads/'),
        ),
    ]
